# Generated by Django 5.2.4 on 2025-08-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(default='', max_length=25, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, db_index=True, verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтвержденная'), ('cancelled', 'Отменённая'), ('completed', 'Выполненная')], default='new', max_length=50, verbose_name='Статус')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['client_name'], name='core_order_client__3038eb_idx'), models.Index(fields=['phone'], name='core_order_phone_582566_idx'), models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'), models.Index(fields=['date_created'], name='core_order_date_cr_d2e958_idx'), models.Index(fields=['status', 'appointment_date'], name='status_appointment_date_idx'), models.Index(fields=['client_name', 'phone'], name='client_name_phone_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_popular', models.BooleanField(blank=True, default=False, verbose_name='Популярная услуга')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'indexes': [models.Index(fields=['price'], name='core_produc_price_c510fe_idx'), models.Index(fields=['is_popular'], name='core_produc_is_popu_a4151b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
