# Generated by Django 5.2.4 on 2025-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_product_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.CharField(choices=[('Вторник', 'Вторник'), ('Пятница', 'Пятница')], default='Вторник', max_length=20, verbose_name='День привоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True, max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='Изображение'),
        ),
    ]
