# Generated by Django 5.2.4 on 2025-08-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_options_order_delivery_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantities',
            field=models.TextField(blank=True, verbose_name='Количество по продуктам (JSON)'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='core.product', verbose_name='Продукты'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
