# Generated by Django 5.2.4 on 2025-08-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_product_quantities_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_quantities',
        ),
        migrations.AddField(
            model_name='order',
            name='products_with_quantity',
            field=models.JSONField(default=dict, verbose_name='Продукты с количеством'),
        ),
    ]
