# Generated by Django 5.2.4 on 2025-08-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_product_quantities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_with_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantities',
            field=models.TextField(blank=True, verbose_name='Количество по продуктам (JSON)'),
        ),
    ]
